
# Site settings
title: Camille 
description: Cool links to cool sites. 
baseurl: "/ch0832a_blog" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "http://ch0832a.github.io" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
